#ifndef LIMITS_H
#define LIMITS_H

#define CHAR_BIT 8
#define UINT_MAX 0xFFFFFFFFU
#define ULONG_MAX 0xFFFFFFFFFFFFFFFFULL
#define INT_MAX 0x7FFFFFFF
#define LONG_MAX 0x7FFFFFFFFFFFFFFFLL

#endif // LIMITS_H
